services:
  judge-app:
    build: .
    container_name: judge-app
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
      - ./client:/app/client
      - /app/client/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MAX_OUTPUT_BYTES=1048576
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "cd /app/server && npm install && npm run dev &
      cd /app/client && npm install && npm run dev"
